name: Workflow CI Andre Kautsar

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow pandas numpy scikit-learn
    - env:
        MLFLOW_TRACKING_URI: file:${{ github.workspace }}/mlruns
      run: |
          mkdir -p mlruns
          mlflow run MLProject --env-manager=local -P data_dir=MLProject/student-performance_preprocessing
